# Title of your blog; shows in the header
name: "a slice of clementine"

# Description of your content (will only be used on Google Search)
description: "Follow the adventures of Clement Hoang through his personal blog, detailing his flavour on lifestyle and tech."

# Your name. Will show in your footer + sidebar
author: "Clement Hoang"

url: "blog.clementhoang.net"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm a software engineering senior at the University of Waterloo. I'm a badminton fanatic, a League enthusiast, an anime lover, and a Javascript monkey. My goal is for this blog to document my learnings and my perspectives."

# Social Accounts
twitter: "https://twitter.com/c8hoang"
github: "https://github.com/clemmy"
linkedin: "https://www.linkedin.com/in/clementhoang"
facebook: "https://www.facebook.com/clemsie"
instagram: "https://instagram.com/cpthoang/"
medium: "https://instagram.com/cpthoang/"

# Google Analytics
ga_domain: blog.clementhoang.net
ga_tracking_id: UA-55816575-1

# Other

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: :title/
# highlighter: rouge

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
